- name: Installing
  ansible.builtin.package:
    name: mysql-server
    state: present

- name: Starting and enabling
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: Installing Python libraries
  ansible.builtin.pip:
    name: "{{ item }}"
    state: present
    executable: pip3.9
  loop:
    - PyMySQL # inorder to use "community.mysql.mysql_info"
    - cryptography # inorder to avoid setting password every time.

- name: Check whether password is set or not
  community.mysql.mysql_info:
    login_user: root
    login_password: "{{ lookup('amazon.aws.aws_ssm', '/expense/mysql/my_root_password', decrypt=True ) }}"
    login_host: mysql.chandev.site
  register: db_info
  ignore_errors: true

- name: Print info
  ansible.builtin.debug:
    msg: "{{ db_info }}"

- name: Setting password
  ansible.builtin.command: mysql_secure_installation --set-root-pass "{{ lookup('amazon.aws.aws_ssm', '/expense/mysql/my_root_password', decrypt=True ) }}"
  when: db_info.failed is true
